/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import com.sun.net.httpserver.HttpServer;
import project.handlers.CheckHandler;
import project.handlers.SumHandler;

import java.io.IOException;
import java.net.InetSocketAddress;
public class App {
    public static void main(String[] args) throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress("0.0.0.0", 5678), 0);

        server.createContext("/", new CheckHandler());
        server.createContext("/sum", new SumHandler());

        server.setExecutor(null); // creates a default executor
        server.start();
    }
}